# Generated by Django 3.1.3 on 2020-12-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
