# Generated by Django 3.1.3 on 2020-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
