# Generated by Django 3.1.3 on 2020-12-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0003_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='photo',
        ),
    ]
