# Generated by Django 3.1.3 on 2020-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0004_business_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cert',
            field=models.ImageField(blank=True, default='cert.jpg', null=True, upload_to='images'),
        ),
    ]
