# Generated by Django 3.1.3 on 2020-12-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0006_auto_20201209_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
