# Generated by Django 3.1.3 on 2020-12-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0007_auto_20201209_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
