# Generated by Django 3.1.3 on 2020-12-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0008_auto_20201209_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
