# Generated by Django 3.1.3 on 2020-12-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='business',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mechanicfinder.business'),
        ),
    ]
