# Generated by Django 3.1.3 on 2020-12-09 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicfinder', '0012_feedback_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datecreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
